# Generated by Django 3.1.2 on 2020-11-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
